PyCon/pycon

- pycon/static/less/site.less
refs #368 
This is a workaround (super duper hack) to fix the issue in #368
> Fix header img margin quirk

- pycon/templates/site_base.html
This commit changes the contact email from pycon-organizers to pycon-reg.
> Change contact e-mail.

- .gitignore
- Makefile
- README.rst
- Vagrantfile
- setup.py
- tox.ini
- vagrant_bootstrap.sh
If your local dev system is newer than Ubuntu 12.04, the
current code won't work (wrong versions of libraries etc.
to build the required python package versions), so this
lets you run a vagrant system that is running Ubuntu
12.04.
There's a little doc added to the README.rst.
> Add some config to do development in a vagrant server

- fabfile.py
The command needs environment variables set in the .env file that is created by Chef. The file is owned by root so we strictly need sudo for this as opposed to run(). The other important change here is sourcing that .env file before invoking manage.py, so that the correct environment variables are set.
Lastly, the --settings= part is redundant with the manage.py we're using everywhere which chooses the proper settings file based on the IS_PRODUCTION environment variable.
> Fixes manage_run fab command

- requirements/project.txt
Pillow 2.0.0 won't build on Ubuntu 14.04.
Pillow 2.9.0 builds on both Ubuntu 12.04 and 14.04, so upgrading
will make it easier to do development.
> Upgrade Pillow to 2.9.0

- pycon/finaid/forms.py
- pycon/migrations/0003_auto_20150731_1306.py
- pycon/models.py
- pycon/profile/forms.py
- pycon/settings/base.py
- pycon/sponsorship/managers.py
- requirements/base.txt
- requirements/project.txt
- symposion/cms/managers.py
- symposion/urls.py
Fix some warnings, including deprecation warnings that come up
when running 'manage.py check' with django 1.7 or django 1.8,
and a 'no logging handler' warning that occurred during tests.
A lot of these just needed upgrading dependencies; a few required
small code changes.
> Fixing some warnings

- requirements/base.txt
Got this error.  According to Dr. Google, we need to use specific versions of django-reversion depending on what version of Django we are using, or this can happen. For Django 1.7+, that's django-reversion 1.9.1 right now (http://django-reversion.readthedocs.org/en/latest/django-versions.html#django-versions).
TypeError: cannot create weak reference to 'int' object
(6 additional frame(s) were not displayed)
...
File "reversion/middleware.py", line 26, in _close_revision
revision_context_manager.end()
File "reversion/revisions.py", line 183, in end
db = self._db,
File "reversion/revisions.py", line 474, in save_revision
revision.save(using=db)
File "reversion/models.py", line 217, in check_for_receivers
if len(sending_signal._live_receivers(_make_id(sender))) > 1:
File …
> TypeError: cannot create weak reference to 'int' object

- fabfile.py
'fab server manage_run:dbshell' was not working. I guess there
wasn't enough information in the Django settings for Django to
invoke psql correctly to connect to our databases the way they
are set up in the PSF infrastructure.
Added a new fab task 'dbshell' that extracts the needed info
the same way we do before running a dump, and invokes psql
directly.  Also tweaked 'manage_run' so if 'dbshell' is passed
as the command, it uses the new task.
> Fix fab dbshell

- pycon/settings/server.py
Google was expecting the redirect_uri to be an https: URL.
We need to set SOCIAL_AUTH_REDIRECT_IS_HTTPS = True on servers
to make that happen.
> Fix social auth for Google

- pycon/sponsorship/tests/test_views.py
- pycon/sponsorship/views.py
This was overlooked when moving the web logo benefit
from its own Benefit record to a field on the Sponsor
model.
Fixes #436
> 436 Fix sponsor logo files zip download

- pycon/static/less/site.less
- pycon/templates/homepage.html
The account buttons on the homepage are now in the top right corner of the page like on the rest of the site.
> homepage account button alignment

- pycon/settings/base.py
Keep connections open and reuse them for up to 5 minutes
by default.
See https://docs.djangoproject.com/en/1.8/ref/databases/#persistent-connections
> Enable persistent database connections

- pycon/tutorials/utils.py
The lists of email addresses were sometimes coming into the
queue_email function as querysets, which the BulkEmail model's
MultiEmail fields couldn't handle. Force them to be lists
when creating the BulkEmail object.
> Fix sending tutorial emails

- pycon/admin.py
- symposion/reviews/views.py
When we added the ability to select multiple proposals
and change their status together, we broke being able
to change the status dropdown on one proposal to change
its status.
> Allow changing status of single proposals

- requirements/base.txt
- tox.ini
Remove insecure extra index URLs from dist.pinaxproject.com
from our requirements files. This always made pip, tox, and
now Read The Docs unhappy. By replacing two package names
in the requirements with direct links to their tarballs
(still on dist.pinaxproject.com), we can get rid of the errors
and warnings.
> Cleanup requirements slightly

- pycon/sponsorship/migrations/0011_auto_20150824_0859.py
- pycon/sponsorship/models.py
On sponsor page, add help to say that the URL must include
http:// or https://.
Also noticed that the "display_url" field, which doesn't
really have to be a URL (it's just used for display), was
a URLField, so changed that to a CharField so sponsors
can just put in "python.org" or something if they prefer
that to "https://python.org".
> Add more help to URL field

- pycon/templates/venue/detail.html
Empty box will allow adding introductory text
above the hotel data.
> Add box on venues page above hotels

- pycon/tutorials/tests/test_utils.py
It was using regular Python unittest.TestCase for some
reason, resulting in leaving old BulkEmail objects in
the database that other tests weren't expecting.
> Use django TestCase in tutorial send email test

- docs/finaid.rst
- pycon/context_processors.py
- pycon/finaid/tests/test_utils.py
- pycon/finaid/tests/test_views.py
- pycon/finaid/utils.py
- pycon/finaid/views.py
- pycon/settings/base.py
- pycon/settings/production.py
- pycon/sponsorship/models.py
- pycon/templates/site_base.html
- symposion/templates/500.html
- symposion/templates/site_base.html
We have a number of email addresses embedded in the code that are sent emails on events (like a new sponsor application being submitted).  The financial aid application makes provision to override the default address using settings, but we're not using that.
The result is probably that the people at the other end of these addresses are getting emailed as we do our testing on local systems and the staging site, and have to ignore these test messages.
We should have all these addresses in settings, and only point them at the real addresses for production. The others should either go nowhere or to the development team by default.
> Move staff email addresses to settings

- symposion/templates/reviews/base.html
It seems that `<div class="span2">` and `<div class="span10">` were too wide for one row, so the second div was being pushed down below the first div.
Fixes #482
> change span10 to span9

- pycon/templates/finaid/confirm.html
Hovering over the "No" button was causing the
"Yes" button to move slightly. Changed the "No"
button to be an actual button wrapped in a link,
rather than just a button-styled link, and that
seemed to fix it.
Fixes #517
> 517 Fix formatting of finaid confirm buttons

- pycon/static/less/site.less
- pycon/templates/account/_openid_sidebar.html
- pycon/templates/account/login.html
- symposion/templates/social_auth/usersocialauth_list.html
These were in a sidebar on the login page, but the parent
template had dropped the sidebar block.  Worked out a way
to get the content displayed roughly the same as last year
with just changes to the login template and very minimal
site.less changes.
Fixes #441
> 441 Display social login links

- pycon/static/less/site.less
> Updates to fonts and scaling on CMS pages

- pycon/static/less/site.less
- pycon/templates/_account_bar.html
- pycon/templates/site_base.html
> Nav and CMS Fixes

- pycon/__init__.py
- pycon/admin.py
- pycon/pyconapp.py
- symposion/proposals/kinds.py
This happened because the forms for the proposal types
don't get registered with our new proposal type registry
until the forms.py file containing them is imported, and
that wasn't happening at startup.
Added a proper Django application initialization that
does the import at startup.
(Note: some code previously in pyconapp.py was removed; it does not seem to ever have been called from anywhere, and adding it to the new `ready` method increased the number of queries on our reviews page view, I guess because it triggered sitetree to do more work on each page. I figured if things were working fine without it, we didn't need it.)
Fixes: #539
> 539 Fix exception creating edusummit proposal

- symposion/reviews/models.py
- symposion/reviews/tests.py
- symposion/reviews/views.py
Added test to recreate problem.
I think this was something that broke when Django was
upgraded, but without a unit test, we weren't aware of
it.
Change from passing a class instance to .update() to
using the (documented) F function to do the same thing
that seemed to be intended.
Also work around Django's annoying behavior of raising
an exception when a reverse relation has no object.
Fixes #551
> 551 Fix error submitting reviews

- pycon/finaid/forms.py
- pycon/finaid/migrations/0009_auto_20150917_1629.py
- pycon/finaid/models.py
- pycon/finaid/tests/test_forms.py
- pycon/finaid/tests/test_views.py
- pycon/finaid/views.py
Fixes #549.
Another thought is whether receipt_image should be renamed to something like receipt_document, since it no longer has to be an image
> allow receipt image to be a pdf by making it a FileField

- pycon/static/less/site.less
- pycon/templates/sponsorship/list.html
added breadcrumbs the sponsor page, fixed double underline on active nav item, and changed H1 on venue pages to title case.
> front end fixes to nav, sponsor list, and venue page

- requirements/project.txt
This includes Django 1.8 support, so we can stop
using our private fork.
Fixes #563
> 563 Use django-constance 1.1

- pycon/templates/homepage.html
A possible fix to the scrollbar issue on the homepage; not sure, though, since unable to recreate issue in local environment
> make flickity wait until images are loaded

- pycon/static/less/site.less
Seems to solve the issue with the scrollbar and the gallery dots beneath the images
> make overflow:visible in container with images

- pycon/models.py
- pycon/program_export.py
- pycon/sponsorship/tests/factories.py
- pycon/sponsorship/tests/test_views.py
- pycon/tests/factories.py
- pycon/tests/test_export.py
- pycon/tests/test_views.py
- pycon/tutorials/tests/test_views.py
- symposion/conference/tests/factories.py
- symposion/proposals/admin.py
- symposion/proposals/apps.py
- symposion/proposals/kinds.py
- symposion/proposals/management/commands/ensure_proposal_records.py
- symposion/proposals/signals.py
- symposion/proposals/tests/test_kinds.py
- symposion/reviews/tests.py
- symposion/schedule/tests/factories.py
This makes sure that for each proposal kind, we have the right
Permission records created.
It also makes sure we have the corresponding Section, ProposalKind,
and ProposalSection records, and even the Conference record for the
current year.
Along the way it has to clean up some miscoding around kind &
section slugs and names. The assumption through here is that the
slugs are the unchanging parts of each proposal kind, while names
could change.
Additionally, a number of tests no longer need to create some
of these records in setup() because they'll already exist, which
might even speed up the tests slightly.
This might seem like overkill, but it's been an ongoing problem.
It's also set up to only run at the end of running migrations, so
there shouldn't be any overhead.
> Fix missing permissions for proposals

- symposion/proposals/models.py
- symposion/proposals/tests/factories.py
- symposion/proposals/tests/test_proposals.py
The way we were checking if a proposal had a presentation
was raising 500s:
File "/srv/pycon/pycon/symposion/proposals/models.py", line 127, in
can_edit
if hasattr(self, "presentation") and self.presentation_id:
AttributeError: 'PyConTalkProposal' object has no attribute
'presentation_id'
Since 'presentation' is a related name and not a foreign key to
the presentation record, there's no 'presentation_id' field.
Change to query the Presentation model directly to see if
there's one that points at this proposal.
Added a test first, verified that it failed, then made this fix
and now the test passes.
> Fix 500 viewing proposal once presentation exists

- symposion/speakers/admin.py
When adding a speaker in the admin, the staff person had to
pick a user from a huge dropdown with all the users, unsorted.
Change 'user' to a raw id field, meaning to pick a user, the staff member clicks a magnifying glass icon next to the field and gets a popup listing all the users in an admin list page with sortable columns and search.
> Fix user selection for speaker add

- pycon/management/commands/update_tutorial_registrants.py
it appears that users can supply a different email to CTE when registering, this caused some tutorial registrants to be missed by the update job. CTE has added a `PyConID` field to their registration CSV which lines up with our User object's `id` field.
> pull User object by id rather than email

- pycon/program_export.py
one of our benefit levels got a `/` which broke the export, guard against future incompatible characters
> program_export: use slugify to get safe names for export files

- pycon/management/commands/bump_unsubmitted_proposals.py
- symposion/templates/emails/proposal_bump/message.html
- symposion/templates/emails/proposal_bump/subject.txt
This can be used to remind folks who have started, but not completed and submitted their proposals!
It's setup so we can use it to bump any proposal type (`talk`, `tutorial`, `poster`, `edusummit`), and we'll run these manually.
cc: @rdodev @jasonamyers @bbengfort @jessingrass
Sample:
> Implement bump_unsubmitted_proposals management command

- Makefile
- fixtures/sitetree_menu.json
- fixtures/sponsorship_benefits.json
- pycon/sponsorship/admin.py
- pycon/sponsorship/migrations/0018_sponsor_job_fair_participant.py
- pycon/sponsorship/models.py
- pycon/sponsorship/templatetags/sponsorship_tags.py
- pycon/static/css/simple-grid.css
- pycon/static/css/slight.css
- pycon/templates/site_base.html
- pycon/templates/sponsorship/email.html
- pycon/templates/sponsorship/jobs.html
Added a `job_fair_participant` `BooleanField` on the `Sponsor` model and make editable in Django Admin.
Dynamically generate an HTML table on the `sponsors/jobs` page with `Sponsor` name and their `job_fair_table_number` _if_ the `Sponsor` is a `job_fair_participant`.
Added Django Template functionality to `Sponsor.send_email` that allows for Django Template logic in Sponsor email sends... Hard to explain 😢 
Non Participant:
Participant:
Address #643 #638
> Job fair participation flag

- pycon/finaid/forms.py
The link for the **I have read the Financial Assistance page** checkbox in the **Apply for Financial Aid** form still points to the 2018 financial assistance page.
> Update financial assistance page link in the financial aid application form

- pycon/management/commands/update_tutorial_registrants.py
- pycon/tests/test_commands.py
- pycon/tutorials/views.py
if the registration vendor returns an email we don't have in our DB for a user:
- associate it in our database
- send tutorial information to that address!
> updates for tutorial registrants and emails

- pycon/views.py
From tutorial offer letter I received the link to secure_submission where I can upload my docs (tax doc and payment info doc).
After submitting one document, I was redirected to dashboard, and could not find the secure submission form anywhere. I had to open up the offer letter again to find the link.
I think it will be better if after submitting the form, people remained on the same page instead of getting redirected to dashboard.
> Redirect to secure_submission after submitting.
