PyCon/pycon

- Vagrantfile
- pycon/finaid/models.py
- pycon/registration/views.py
- pycon/settings/base.py
- pycon/tests/base.py
- requirements/base.txt
- requirements/dev.txt
- requirements/project.txt
- symposion/cms/views.py
- symposion/reviews/models.py
- tox.ini
Review after https://github.com/PyCon/pycon/pull/404 has been merged; until then, this pull will show changes from both.
> Django16 on ubuntu1204

- README.rst
> Updates to README re: vagrant

- docs/sponsorship.rst
- pycon/settings/base.py
- pycon/sponsorship/admin.py
- pycon/sponsorship/forms.py
- pycon/sponsorship/managers.py
- pycon/sponsorship/migrations/0002_sponsor_contact_emails.py
- pycon/sponsorship/migrations/0003_migrate_contact_emails.py
- pycon/sponsorship/migrations/0004_remove_sponsor_contact_email.py
- pycon/sponsorship/models.py
- pycon/sponsorship/tests/factories.py
- pycon/sponsorship/tests/test_forms.py
- pycon/sponsorship/tests/test_views.py
- pycon/sponsorship/views.py
- requirements/base.txt
- symposion/templates/emails/sponsor_signup/message.html
Must be at least one
Fixes: #381
> 381 Allow multiple contact emails for a sponsor

- pycon/settings/base.py
- requirements/project.txt
This is the client for Sentry
Fixes # 335
> 335 Update raven to 5.5.0

- pycon/settings/server.py
- pycon/static/less/bootstrap/mixins.less
rehash of non fabfile changes from #430
> fixups for salt deploy

- fabfile.py
- pycon/management/commands/sqldsn.py
rehash of fabfile changes from #430 
merge this when we've migrated to the new infrastructure.
> fabfile changes for new infrastucture

- pycon/program_export.py
- pycon/tests/test_export.py
When doing the Program Export (bottom of dashboard), include the abstract's
contents in both the schedule and presentation export files.
Fixes #396
> 396 Include abstract in program export

- pycon/settings/production.py
This couldn't have been good for performance.
> Turn off debug logging in production

- pycon/pycon_api/tests.py
- pycon/pycon_api/urls.py
- pycon/pycon_api/views.py
- pycon/tests/factories.py
Wanted to add tests for the current API to help when
starting to convert it to Django REST framework later.
> Add tests for thunderdomegroup API

- pycon/static/less/site.less
- pycon/static/less/variables-site-colors.less
I updated the color palette to match the site design and removed unused colors from the variables-site-colors.less file. This includes updates the tan background color to #fef8ec per Brandon's request.
> Updated site button colors to match new color palette.

- pycon/pycon_api/decorators.py
- pycon/pycon_api/tests.py
- pycon/schedule/management/commands/create_schedule.py
- pycon/schedule/tests/factories.py
- pycon/schedule/tests/test_session_staff_json.py
- pycon/schedule/tests/test_views.py
- pycon/schedule/urls.py
- pycon/schedule/views.py
Requires an API key; see the API docs once they've
been updated.
> 390 Add an API to return session chairs and runners

- pycon/settings/server.py
Right now, the general cache and the session cache are in the
same DB, so if we want to clear cached pages, it results in everyone's
sessions (and logins) being deleted.
By putting the sessions in a different Redis DB, we should
be able to clear the general cache without affecting sessions.
> Move session cache to a different Redis DB

- docs/translation.rst
- pycon/settings/base.py
- symposion/cms/admin.py
- symposion/cms/forms.py
- symposion/cms/views.py
- symposion/views.py
Arrange so turning off the USE_I18N setting will disable
French on the site.
Also, turn off the USE_I18N setting.
Fixes: #497
> 497 Disable French

- pycon/static/less/site.less
Addressing issues from Brandon regarding the styling of the main navigation and account links. This branch fixes alignment issues with the small logo, main nav links, and account links. This branch also addresses the height of the account links so they now span from the top of the screen to the top of the green breadcrumbs bar.
> Fixing issues with the main navigation and account bar styling.

- pycon/forms.py
- pycon/migrations/0004_edusummittalkproposal.py
- pycon/models.py
- symposion/conference/models.py
- symposion/reviews/tests.py
- symposion/reviews/views.py
> 494 Add talk type for Education Summit

- pycon/forms.py
- pycon/tests/test_views.py
They were getting saved as lightning talks
Fixes #544
> 544 Fix edusummit proposal type

- pycon/tests/factories.py
- pycon/tests/test_views.py
- symposion/conference/models.py
- symposion/conference/tests/factories.py
- symposion/proposals/kinds.py
- symposion/proposals/models.py
- symposion/proposals/tests/factories.py
- symposion/reviews/tests.py
- symposion/reviews/views.py
- symposion/schedule/models.py
- symposion/schedule/tests/factories.py
For edusummit proposals especially.
The fix is really the 3 lines changed to 1
in reviews/views.py, but adding a test for this
problem turned up some inconsistencies in other
places that I went ahead and addressed.
I also fixed any PEP-8 problems in the files that
I was changing anyway.
Fixes #547
> 547 Fix error when changing proposal status

- pycon/models.py
I need additional requirements and category; once again, I can't test this locally!
@lukesneeringer could you sanity check this for me?
> The two missing pieces of talk export

- pycon/models.py
exporting additional reqs & categories to production branch
> Moving API tweak to production

- pycon/finaid/admin.py
A low effort pass at resolving the need for administrators to view/access Financial Aid Aplicant Receipt data/media.
> Adds an admin interface for Financial Aid Receipts

- pycon/admin.py
sorts by (last_name, first_name), I also updated the display in django admin to hide the rather useless auto-generated usernames.
> update ordering for user drop down to be more friendly

- pycon/finaid/tests/test_forms.py
- pycon/finaid/tests/test_models.py
- pycon/finaid/tests/test_utils.py
- pycon/finaid/tests/test_views.py
- pycon/finaid/tests/utils.py
- pycon/pycon_api/tests.py
- pycon/registration/tests/test_views.py
- pycon/templates/registration/login.html
- pycon/tests/factories.py
- pycon/tests/test_commands.py
- pycon/tutorials/tests/test_views.py
- symposion/reviews/tests.py
- symposion/templates/site_base.html
attempting to get all existing tests passing again.
> test fixups

- docker-compose.yml
- pycon/settings/base.py
- pycon/static/css/slight.css
- requirements/project.txt
- symposion/speakers/forms.py
- symposion/speakers/migrations/0006_speaker_profile_flags.py
- symposion/speakers/models.py
Hello @jasonamyers, @lorenanicole, @jackiekazil!
I'd like to welcome your feedback on collecting some new booleanish fields during creation of speaker profiles.
Screencap of how this appears as of 5f9b92199ebc8a6e3f9b8eaf69e6169711c14566:
> add some new flags to speaker profiles!

- .travis.yml
- pycon/static/css/slight.css
- pycon/templates/sponsorship/jobs.html
- tidy up group registrations page
- fix travis tests
- prep the jobs page
> Fixups 2017 12 13

- pycon/admin.py
- pycon/settings/base.py
- requirements/base.txt
- requirements/project.txt
- symposion/boxes/admin.py
- symposion/cms/admin.py
- symposion/reviews/templatetags/review_tags.py
- symposion/speakers/admin.py
- symposion/templates/proposals/_proposal_fields.html
- symposion/templates/reviews/review_detail.html
Address #636 and other various Markdowny things.
> markdownify!

- pycon/static/css/slight.css
- pycon/templates/site_base.html
- symposion/templates/reviews/base.html
keep the reviews panel from floating away to the right forever.
> improve the life of our reviewers

- pycon/finaid/forms.py
- pycon/finaid/migrations/0012_updates_to_finaidreviewdata.py
- pycon/finaid/models.py
- pycon/finaid/tests/test_views.py
- pycon/finaid/views.py
- pycon/templates/finaid/confirm.html
> collect some basic data when folks accept their offer.

- pycon/program_export.py
Program export was updated from exporting only tutorial and talk schedules to all schedules so it would include the Education Summit Schedule and Sponsor Tutorial Schedule.
> Include all schedules and not just tutorial and talk schedules

- pycon/program_export.py
- pycon/templates/dashboard.html
- added photo url export to speaker exporter in /pycon/program_export.py
- split out time and date from special event exported in /pycon/program_export.py
- changed display name of program export button on /pycon/templates/dashboard.html
> Program export enhancements

- pycon/forms.py
- pycon/migrations/0012_pyconcharlaproposal.py
- pycon/models.py
- pycon/templates/proposals/proposal_submit_kind.html
- symposion/templates/proposals/_proposal_fields.html
> add PyCon Charlas CFP submission

- pycon/mentorship/admin.py
- pycon/mentorship/management/commands/finalize_sessions.py
- pycon/mentorship/management/commands/import_availability.py
- pycon/mentorship/management/commands/invite_mentees.py
- pycon/mentorship/migrations/0001_initial.py
- pycon/mentorship/models.py
- pycon/mentorship/urls.py
- pycon/mentorship/utils.py
- pycon/mentorship/views.py
- pycon/settings/base.py
- pycon/templates/dashboard.html
- pycon/templates/mentorship/email/mentee_invitation/body.txt
- pycon/templates/mentorship/email/mentee_invitation/subject.txt
- pycon/templates/mentorship/email/scheduling_failed/body.txt
- pycon/templates/mentorship/email/scheduling_failed/subject.txt
- pycon/templates/mentorship/email/session_confirmed/body.txt
- pycon/templates/mentorship/email/session_confirmed/subject.txt
- pycon/templates/mentorship/mentorship_signup_recieved.html
- pycon/templates/mentorship/mentorship_slots_view.html
- symposion/urls.py
bits and bobs for managing PyCon proposal mentorship program.
> Mentorship

- pycon/finaid/admin.py
- pycon/finaid/migrations/0013_financialaidapplication_application_type.py
- pycon/finaid/models.py
> financial aid: add a flag for application type

- pycon/forms.py
- pycon/migrations/0014_auto_20190130_1601.py
- pycon/models.py
- pycon/views.py
- Add logo field
- Add approval field
- Allow users to return/edit/update
- Disable user edits after acceptance
> startuprow application touchups

- pycon/finaid/context_processors.py
- pycon/finaid/forms.py
- pycon/finaid/migrations/0014_auto_20190312_1503.py
- pycon/finaid/models.py
- pycon/finaid/tests/test_forms.py
- pycon/finaid/tests/test_views.py
- pycon/templates/finaid/receipt_upload.html
- requirements/base.txt
reduce overhead for finaid staff reviewing receipts
> finaid: add additional fields to receipt upload form

- pycon/admin.py
- pycon/forms.py
- pycon/migrations/0017_securesubmission.py
- pycon/models.py
- pycon/settings/local.py-heroku
- pycon/urls.py
- pycon/views.py
- requirements/project.txt
will allow accounting team to securely request information and documents
> create secure_submissions endpoint that encrypts submissions at rest

- pycon/schedule/admin.py
- pycon/schedule/forms.py
- pycon/schedule/migrations/0002_slidesupload.py
- pycon/schedule/models.py
- pycon/schedule/urls.py
- pycon/schedule/views.py
- pycon/templates/dashboard.html
- pycon/templates/pycon/schedule/slides_upload.html
Provides a way for Presenters to upload slides for their talk! Shows up in dashboard if speaker has a presentation.
We can determine how we present/deliver these to our captioner... @bcostlow can you help with direction for that?
> Slides upload

- pycon/schedule/models.py
- pycon/schedule/urls.py
- pycon/schedule/views.py
- pycon/templates/pycon/schedule/slides_download.html
@ewdurbin Slide download code.
> Slides download

- pycon/schedule/views.py
I think, I could not get orig code to behave the same way as real site.
@ewdurbin
> Fix for sorting issue with captioner downloads.

- pycon/schedule/views.py
> Revert "Fix for sorting issue with captioner downloads."
